[package]
name = "rconfig"
version = "0.1.0"
edition = "2021"

[dependencies]
basic-toml = "0.1.9"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.0" }
convert_case = "0.6.0"
