# something without a type is just a menu item
[options]
description = "Options"

# something with a type is something which can be configured
[options.options.ble]
description = "Enable Bluetooth Low Energy"
type = "bool"
default = false

[options.options.buffer]
description = "BLE Buffer Size"
depends = "enabled(\"options.ble\")"
type = "enum"
values = [
    { description = "1k", value = "1" },
    { description = "2k", value = "2" },
    { description = "4k", value = "4" },
]
default = "1"
